/* MENU */
export const STORE_MENU = 'STORE_MENU'

/* USERS */
export const STORE_ME = 'STORE_ME'
export const STORE_USER = 'STORE_USER'
export const STORE_USERS = 'STORE_USERS'
export const UPDATE_USER = 'UPDATE_USER'

/* IMAGES */
export const ADD_IMAGE_CATEGORY = 'ADD_IMAGE_CATEGORY'
export const ADD_IMAGE_SERIES = 'ADD_IMAGE_SERIES'
export const STORE_IMAGE = 'STORE_IMAGE'
export const STORE_IMAGE_CATEGORY = 'STORE_IMAGE_CATEGORY'
export const STORE_IMAGE_CATEGORIES = 'STORE_IMAGE_CATEGORIES'
export const DELETE_IMAGE = 'DELETE_IMAGE'
export const DELETE_IMAGE_SERIES = 'DELETE_IMAGE_SERIES'
export const DELETE_IMAGE_CATEGORY = 'DELETE_IMAGE_CATEGORY'
export const UPDATE_IMAGE_SERIES_SORT_ORDER = 'UPDATE_IMAGE_SERIES_SORT_ORDER'
