/* MENU */
export const STORE_MENU = 'STORE_MENU'
export const TOGGLE_MENU = 'TOGGLE_MENU'

/* USERS */
export const STORE_ME = 'STORE_ME'
export const STORE_USER = 'STORE_USER'
export const STORE_USERS = 'STORE_USERS'
export const UPDATE_USER = 'UPDATE_USER'
export const STORE_TOKEN = 'STORE_TOKEN'
export const REMOVE_TOKEN = 'REMOVE_TOKEN'

/* IMAGES */
export const ADD_IMAGE_CATEGORY = 'ADD_IMAGE_CATEGORY'
export const ADD_IMAGE_SERIES = 'ADD_IMAGE_SERIES'
export const STORE_IMAGE = 'STORE_IMAGE'
export const STORE_IMAGE_CATEGORY = 'STORE_IMAGE_CATEGORY'
export const STORE_IMAGE_CATEGORIES = 'STORE_IMAGE_CATEGORIES'
export const DELETE_IMAGE = 'DELETE_IMAGE'
export const DELETE_IMAGE_SERIES = 'DELETE_IMAGE_SERIES'
export const DELETE_IMAGE_CATEGORY = 'DELETE_IMAGE_CATEGORY'
export const UPDATE_IMAGE_SERIES_SORT_ORDER = 'UPDATE_IMAGE_SERIES_SORT_ORDER'

/* PAGES */
export const STORE_PAGE = 'STORE_PAGE'
export const STORE_PAGES = 'STORE_PAGES'
export const DELETE_PAGE = 'DELETE_PAGE'

export const STORE_PAGE_FRAGMENT = 'STORE_PAGE_FRAGMENT'
export const STORE_PAGE_FRAGMENTS = 'STORE_PAGE_FRAGMENTS'
export const DELETE_PAGE_FRAGMENT = 'DELETE_PAGE_FRAGMENT'
